kind: pipeline
name: default

steps:
- name: elastic_sh
  image: rust:1.42.0
  commands:
  - rustup component add clippy
  - cargo clippy --workspace
  - cargo test --workspace

services:
  - name: elasticsearch
    image: elasticsearch:7.6.2
    port: 9200
    environment:
      discovery.type: single-node
